### ISSUE TITLE
there's no  train_point_corr.py 

### ISSUE THREAD

**Issue by Kiswelrg** [OpenSpaceAI/SE-ORNet#2]

**Comment by Kiswelrg** [comment]
nice guys fake codes

**Comment by JiachengDeng** [comment]
Apologies for the typo in our README.md document. The correct main file is denoted as _train.py_ as opposed to _train_point_corr.py_. Furthermore, we have included the entire source code along with the associated pre-trained model. Please do not hesitate to reach out with any additional inquiries or concerns.
