### ISSUE TITLE
About the valid_pairs of the SMAL datasets 

### ISSUE THREAD

**Issue by 2019EPWL** [OpenSpaceAI/SE-ORNet#3]
May I ask, when smal is used as the training set in this work, is the pair of correspondence point clouds composed of the intra-class of animals or of the inter-class

**Comment by black-prince222** [comment]
hello, may I ask, what is the visualization tool you use for drawing the qualitative result?

**Comment by JiachengDeng** [comment]
> May I ask, when smal is used as the training set in this work, is the pair of correspondence point clouds composed of the intra-class of animals or of the inter-class

Intra-class.

**Comment by JiachengDeng** [comment]
> hello, may I ask, what is the visualization tool you use for drawing the qualitative result?

Open3d and Mitsuba.

**Comment by 2019EPWL** [comment]
> > May I ask, when smal is used as the training set in this work, is the pair of correspondence point clouds composed of the intra-class of animals or of the inter-class
> 
> Intra-class.

Similarly, if the training set of tosca is also intra-class, the training dataset and the testing dataset of tosca are not exactly the same？

**Comment by JiachengDeng** [comment]
> > > May I ask, when smal is used as the training set in this work, is the pair of correspondence point clouds composed of the intra-class of animals or of the inter-class
> > 
> > 
> > Intra-class.
> 
> Similarly, if the training set of tosca is also intra-class, the training dataset and the testing dataset of tosca are not exactly the same？

Yes, we maintained the same setup as in our previous work. Given that this is an unsupervised task, we do not have annotated data during the training process.
